"""
Export System for TERRAQORE
Enables exporting projects, code, and achievements in multiple formats
"""

from dataclasses import dataclass
from typing import Dict, Any, Optional, List
from datetime import datetime
import json
from enum import Enum


class ExportFormat(Enum):
    """Supported export formats"""
    MARKDOWN = "markdown"
    JSON = "json"
    CSV = "csv"
    HTML = "html"


@dataclass
class ExportOptions:
    """Options for project export"""
    include_artifacts: bool = True
    include_achievements: bool = True
    include_metrics: bool = True
    include_code_snippets: bool = False
    include_timeline: bool = True
    format: ExportFormat = ExportFormat.MARKDOWN


class ExportManager:
    """
    Manages export of projects, achievements, and code artifacts
    """
    
    def __init__(self):
        """Initialize export manager"""
        self.exports_directory = "exports"
    
    def export_project_summary(
        self,
        project_data: Dict[str, Any],
        attribution_summary: Optional[Dict[str, Any]] = None,
        achievements: Optional[List[Dict[str, Any]]] = None,
        options: Optional[ExportOptions] = None
    ) -> str:
        """Export complete project summary"""
        
        if options is None:
            options = ExportOptions()
        
        if options.format == ExportFormat.MARKDOWN:
            return self._export_to_markdown(
                project_data,
                attribution_summary,
                achievements,
                options
            )
        elif options.format == ExportFormat.JSON:
            return self._export_to_json(
                project_data,
                attribution_summary,
                achievements,
                options
            )
        elif options.format == ExportFormat.HTML:
            return self._export_to_html(
                project_data,
                attribution_summary,
                achievements,
                options
            )
        else:
            return self._export_to_json(
                project_data,
                attribution_summary,
                achievements,
                options
            )
    
    def _export_to_markdown(
        self,
        project_data: Dict[str, Any],
        attribution_summary: Optional[Dict[str, Any]],
        achievements: Optional[List[Dict[str, Any]]],
        options: ExportOptions
    ) -> str:
        """Export project to Markdown format"""
        
        md = f"""# Project: {project_data.get('name', 'Unknown')}

**Project ID**: {project_data.get('id', 'N/A')}  
**Status**: {project_data.get('status', 'unknown')}  
**Completion**: {project_data.get('completion_percentage', 0)}%  
**Created**: {project_data.get('created_at', 'N/A')}  

## Description

{project_data.get('description', 'No description provided')}

## Project Statistics

- **Total Tasks**: {project_data.get('task_count', 0)}
- **Completion Status**: {project_data.get('completion_percentage', 0)}%

"""
        
        # Add achievements section
        if options.include_achievements and achievements:
            md += f"""## Achievements 🏆

"""
            for achievement in achievements:
                md += f"- {achievement.get('icon', '⭐')} **{achievement.get('badge_name', 'Unknown')}** - {achievement.get('description', '')}\n"
            md += "\n"
        
        # Add attribution section
        if options.include_artifacts and attribution_summary:
            md += f"""## Generated Artifacts

**Total Artifacts**: {attribution_summary.get('total_artifacts', 0)}

### By Type

"""
            for artifact_type, count in attribution_summary.get('by_type', {}).items():
                md += f"- {artifact_type}: {count}\n"
            
            md += f"""
### By Generation Level

"""
            for level, count in attribution_summary.get('by_level', {}).items():
                md += f"- {level}: {count}\n"
            
            if attribution_summary.get('average_quality_score'):
                md += f"""
### Quality Metrics

- **Average Quality Score**: {attribution_summary['average_quality_score']}/10
- **Average Test Coverage**: {attribution_summary.get('average_test_coverage', 0)}%

"""
        
        # Add agents section
        if options.include_artifacts and attribution_summary:
            md += f"""## AI Agents Involved

"""
            for agent, count in attribution_summary.get('by_agent', {}).items():
                md += f"- **{agent}**: {count} artifacts\n"
            md += "\n"
        
        # Add footer
        md += f"""---

*Export generated by TERRAQORE v1.0 on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*  
[TERRAQORE Documentation](https://github.com/TERRAQORE)
"""
        
        return md
    
    def _export_to_json(
        self,
        project_data: Dict[str, Any],
        attribution_summary: Optional[Dict[str, Any]],
        achievements: Optional[List[Dict[str, Any]]],
        options: ExportOptions
    ) -> str:
        """Export project to JSON format"""
        
        export_data = {
            'export_timestamp': datetime.now().isoformat(),
            'export_format_version': '1.0',
            'generated_by': 'TERRAQORE v1.0',
            'project': project_data,
        }
        
        if options.include_achievements and achievements:
            export_data['achievements'] = achievements
        
        if options.include_artifacts and attribution_summary:
            export_data['artifacts'] = attribution_summary
        
        return json.dumps(export_data, indent=2)
    
    def _export_to_html(
        self,
        project_data: Dict[str, Any],
        attribution_summary: Optional[Dict[str, Any]],
        achievements: Optional[List[Dict[str, Any]]],
        options: ExportOptions
    ) -> str:
        """Export project to HTML format"""
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TERRAQORE Project Export: {project_data.get('name', 'Unknown')}</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            background: #f5f5f5;
            padding: 20px;
        }}
        .container {{
            max-width: 1000px;
            margin: 0 auto;
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            padding: 40px;
        }}
        h1 {{
            color: #2c3e50;
            margin-bottom: 20px;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #34495e;
            margin-top: 30px;
            margin-bottom: 15px;
        }}
        .stats {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin: 20px 0;
        }}
        .stat-card {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            border-radius: 8px;
            text-align: center;
        }}
        .stat-card h3 {{
            font-size: 14px;
            opacity: 0.9;
            margin-bottom: 10px;
        }}
        .stat-card .value {{
            font-size: 28px;
            font-weight: bold;
        }}
        .achievements {{
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
            gap: 15px;
            margin: 20px 0;
        }}
        .achievement {{
            background: #f8f9fa;
            border: 2px solid #dee2e6;
            border-radius: 8px;
            padding: 15px;
            text-align: center;
        }}
        .achievement-icon {{
            font-size: 32px;
            margin-bottom: 10px;
        }}
        .achievement-name {{
            font-weight: bold;
            color: #2c3e50;
            font-size: 14px;
        }}
        footer {{
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #dee2e6;
            font-size: 12px;
            color: #7f8c8d;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🎯 {project_data.get('name', 'Unknown Project')}</h1>
        
        <p><strong>ID:</strong> {project_data.get('id', 'N/A')}</p>
        <p><strong>Status:</strong> {project_data.get('status', 'unknown')}</p>
        <p><strong>Created:</strong> {project_data.get('created_at', 'N/A')}</p>
        
        <h2>Description</h2>
        <p>{project_data.get('description', 'No description provided')}</p>
        
        <h2>Statistics</h2>
        <div class="stats">
            <div class="stat-card">
                <h3>Completion</h3>
                <div class="value">{project_data.get('completion_percentage', 0)}%</div>
            </div>
            <div class="stat-card">
                <h3>Tasks</h3>
                <div class="value">{project_data.get('task_count', 0)}</div>
            </div>
"""
        
        if attribution_summary:
            html += f"""            <div class="stat-card">
                <h3>Artifacts</h3>
                <div class="value">{attribution_summary.get('total_artifacts', 0)}</div>
            </div>
"""
        
        html += """        </div>
"""
        
        if options.include_achievements and achievements:
            html += """        <h2>🏆 Achievements</h2>
        <div class="achievements">
"""
            for achievement in achievements:
                html += f"""            <div class="achievement">
                <div class="achievement-icon">{achievement.get('icon', '⭐')}</div>
                <div class="achievement-name">{achievement.get('badge_name', 'Unknown')}</div>
            </div>
"""
            html += """        </div>
"""
        
        html += f"""        <footer>
            <p>Generated by <strong>TERRAQORE v1.0</strong> on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            <p><a href="https://github.com/TERRAQORE">TERRAQORE Documentation</a></p>
        </footer>
    </div>
</body>
</html>
"""
        
        return html


# Global singleton instance
_export_manager: Optional[ExportManager] = None


def get_export_manager() -> ExportManager:
    """Get or create the global export manager instance"""
    global _export_manager
    if _export_manager is None:
        _export_manager = ExportManager()
    return _export_manager
